export const cards = [
  {
    id: "PG-001",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-002",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-003",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-004",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-005",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-006",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-007",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-008",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-009",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-010",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-011",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-012",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-013",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-014",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-015",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-016",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-017",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-018",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-019",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-020",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-021",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-022",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-023",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-024",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-025",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-026",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-027",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-028",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-029",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-030",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-031",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-032",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-033",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-034",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-035",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
  {
    id: "PG-036",
    name: "PG RX-78-2 Gundam",
    grade: "PG",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71fXBvrpKQL._AC_SX679_.jpg",
  },
  {
    id: "SD-037",
    name: "SD Strike Freedom Gundam",
    grade: "SD",
    series: "Seed",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/sd-gundam-ex-standard-strike-freedom-gundam-pa_1.jpg?v=1632839588",
  },
  {
    id: "MG-038",
    name: "MG Gundam Barbatos",
    grade: "MG",
    series: "IBO",
    image:
      "https://cdn.shopify.com/s/files/1/2786/5582/products/191_3419_s_to0m866o5x5p8duhwc8b2f6wjvxz_clipped_rev_1.png?v=1654125452",
  },
  {
    id: "HG-039",
    name: "HG Gundam Aerial",
    grade: "HG",
    series: "WFM",
    image: "https://i.redd.it/tq8tix7ndaua1.jpg",
  },
  {
    id: "HARO-040",
    name: "Haro Basic Green",
    grade: "Other",
    series: "UC",
    image: "https://m.media-amazon.com/images/I/71BH1f+fplL.jpg",
  },
];
