export const kits = [
  { name: "HG Strike Freedom", status: "completed" },
  { name: "SD Gundam Nobunaga", status: "completed" },
  { name: "HG Infinite Justice", status: "completed" },
  { name: "HG Barbatos Lupus", status: "completed" },
  { name: "HG Ryusei-Go Graze", status: "completed" },
  { name: "SD Freedom Gundam", status: "completed" },
  { name: "Frame Arms Girls Jinghu", status: "completed" },
  { name: "RG Gundam Mk-II Titans", status: "completed" },
  { name: "HG Gundam Ez-8", status: "completed" },
  { name: "SD Gundam Aerial", status: "completed" },
  { name: "30 Minute Sisters Lirinel Color A", status: "completed" },
  { name: "HG Gundam Aerial", status: "completed" },
  { name: "Haro Basic Green", status: "completed" },
  { name: "HG Darilbalde", status: "completed" },
  { name: "HG ChuChu's Demi Trainer", status: "completed" },
  { name: "SD Unicorn Gundam", status: "completed" },

  { name: "HG Gundam Ground Type", status: "backlog" },
  { name: "HG Guel's Dilanza", status: "backlog" },
  { name: "MG Barbatos", status: "backlog" },
  { name: "HG Gundam Lfrith", status: "backlog" },
  { name: "HG Gundam Aerial Neon", status: "backlog" },
  { name: "HG Gundam Ball Twin Set", status: "backlog" },
  { name: "PG Unleashed RX-78-2 Gundam", status: "backlog" },
  { name: "HG Gundam Flauros Ryusei-Go", status: "backlog" },
  { name: "HG Gundam Schwarzette", status: "backlog" },
  { name: "HG Gundam Calibarn", status: "backlog" },
  { name: "SD Nu Gundam", status: "backlog" },
  { name: "SD Astray Red Frame", status: "backlog" },

  { name: "HG Michaelis", status: "wishlist" },
  { name: "Full Mechanics Gundam Aerial", status: "wishlist" },
  { name: "RG RX-78-2 2.0", status: "wishlist" },
  { name: "RG Nu Gundam", status: "wishlist" },
  { name: "RG Hi-Nu Gundam", status: "wishlist" },
  { name: "MG RX-78-2 2.0", status: "wishlist" },
  { name: "MGEX Unicorn Gundam", status: "wishlist" },
  { name: "MGEX Strike Freedom Gundam", status: "wishlist" },
  { name: "PG Unleashed Nu Gundam", status: "wishlist" },
];
